----------------
---USER
----------------

CREATE TABLE IF NOT EXISTS USERS (
  ID_USER INT(11) NOT NULL AUTO_INCREMENT,
  ACTIVO TINYINT(1) NOT NULL, 
  CORREO VARCHAR(100) NOT NULL UNIQUE,
  FECHA_CREACION TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP,
  PRIMARY KEY (ID_USER)
);

----------------
---ROLE
----------------

CREATE TABLE IF NOT EXISTS ROLES(
  ID_ROLE INT(11) NOT NULL AUTO_INCREMENT,
  ROLE VARCHAR(50) NOT NULL,
  ROLE_DESC VARCHAR(250),
  ID_USER INT(11) NOT NULL,
  PRIMARY KEY (ID_ROLE),
    CONSTRAINT FK_USER_ID_ROLE
    FOREIGN KEY (ID_USER)
    REFERENCES USERS (ID_USER)
);

----------------
---CONTRIBUYENTES
----------------

CREATE TABLE IF NOT EXISTS CONTRIBUYENTES (
  ID_CONTRIBUYENTE INT(11) NOT NULL AUTO_INCREMENT,
  RFC VARCHAR(15) NOT NULL,
  GIRO VARCHAR(50),
  NOMBRE VARCHAR(50),
  CURP VARCHAR(20),
  RAZON_SOCIAL VARCHAR(100) ,
  REGIMEN_FISCAL VARCHAR(500) ,
  CALLE VARCHAR(100) ,
  NO_EXTERIOR VARCHAR(50) ,
  NO_INTERIOR VARCHAR(50) ,
  COLONIA VARCHAR(50) ,
  MUNICIPIO VARCHAR(50) ,
  LOCALIDAD VARCHAR(50) ,
  ESTADO VARCHAR(50) ,
  PAIS VARCHAR(50) ,
  COO VARCHAR(50) ,
  CODIGO_POSTAL VARCHAR(50) ,
  CORREO VARCHAR(100) ,
  TELEFONO VARCHAR(15) ,
  FECHA_CREACION TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP,
  PRIMARY  KEY (ID_CONTRIBUYENTE),
  UNIQUE (RFC)
);

----------------
---EMPRESAS
----------------

CREATE TABLE IF NOT EXISTS EMPRESAS (
  ID_EMPRESA INT(11) NOT NULL AUTO_INCREMENT,
  LINEA VARCHAR(5) NOT NULL,
  GIRO_ID INT(10) NOT NULL,
  ACTIVO TINYINT(1),
  RFC VARCHAR(15) NOT NULL,
  REGIMEN_FISCAL VARCHAR(15) NOT NULL,
  CONTACTO_ADMIN VARCHAR(50),
  REFERENCIA VARCHAR(200),
  SUCURSAL VARCHAR(50),
  LUGAR_EXPEDICION VARCHAR(100),
  PW_CORREO VARCHAR(50),
  WEB VARCHAR(150),
  CORREO VARCHAR(50),
  ENCABEZADO VARCHAR(250) ,
  PIE_DE_PAGINA VARCHAR(250) ,
  NO_CERTIFICADO VARCHAR(30),
  PW_SAT VARCHAR(50),
  FECHA_CREACION TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP,
  PRIMARY KEY (ID_EMPRESA),
  UNIQUE (RFC)
);

----------------
---CLIENT
----------------

CREATE TABLE IF NOT EXISTS CLIENTES (
  ID_CLIENTE INT(11) NOT NULL AUTO_INCREMENT,
  RFC VARCHAR(50) UNIQUE NOT NULL,
  CORREO_PROMOTOR VARCHAR(50) NOT NULL,
  CORREO_CONTACTO VARCHAR(50) NOT NULL,
  ACTIVO TINYINT(1),
  PORCENTAJE_PROMOTOR INT(3),
  PORCENTAJE_CLIENTE  INT(3),
  PORCENTAJE_CONTACTO INT(3),
  PORCENTAJE_DESPACHO INT(3),
  FECHA_CREACION TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP,
  PRIMARY KEY (ID_CLIENTE),
  UNIQUE (RFC)
);

CREATE TABLE IF NOT EXISTS PAGOS(
	CREATE TABLE `PAGOS` (
  `ID_PAGO` int NOT NULL AUTO_INCREMENT,
  `FOLIO` varchar(40) NOT NULL,
  `FOLIO_PADRE` varchar(50) NULL,
  `MONEDA` varchar(5) NOT NULL,
  `BANCO` varchar(40) NOT NULL,
  `CUENTA` varchar(30) NOT NULL,
  `TIPO_CAMBIO` decimal(12,2) NOT NULL,
  `FORMA_PAGO` varchar(40) NOT NULL,
  `MONTO` decimal(20,2) unsigned NOT NULL,
  `ACREDOR` varchar(20) NOT NULL,
  `DEUDOR` varchar(20) NOT NULL,
  `STATUS_PAGO` varchar(20) NOT NULL,
  `COMENTARIO_PAGO` varchar(250) NULL,
  `SOLICITANTE` varchar(50) NOT NULL,
  `REVISION_1` tinyint NULL,
  `REVISION_2` tinyint NULL,
  `REVISOR_1` varchar(50) NULL,
  `REVISOR_2` varchar(50) NULL,
  `FECHA_CREACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FECHA_PAGO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FECHA_ACTUALIZACION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_PAGO`),
  UNIQUE KEY `FOLIO_UNIQUE` (`FOLIO`,`FORMA_PAGO`)
);



CREATE TABLE IF NOT EXISTS `INGRESOS` (
  `ID_INGRESO` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `MONTO` decimal(20,2) unsigned NOT NULL,
  `FORMA_PAGO` varchar(20) COLLATE utf8_spanish_ci NOT NULL,
  `CUENTA` varchar(100) COLLATE utf8_spanish_ci NOT NULL,
  `BANCO` varchar(100) COLLATE utf8_spanish_ci NOT NULL,
  `MONEDA` varchar(10) COLLATE utf8_spanish_ci NOT NULL,
  `TIPO_CAMBIO` decimal(10,2) unsigned NOT NULL,
  `FECHA_PAGO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FECHA_CREACION` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `FECHA_ACTUALIZACION` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID_INGRESO`)
);


CREATE TABLE IF NOT EXISTS DEVOLUCIONES(
  ID_DEVOLUCION INT(11) NOT NULL AUTO_INCREMENT,
  ID_PAGO INT(11),
  FOLIO VARCHAR(40) NOT NULL,
  MONTO DOUBLE NOT NULL,
  STATUS_DEVOLUCION VARCHAR(20),
  ID_RECEPTOR VARCHAR(40) NOT NULL,
  TIPO_RECEPTOR VARCHAR(40) NOT NULL,
  FECHA_CREACION TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP,
  PRIMARY KEY (ID_DEVOLUCION)
);


----------------
---FACTURA TABLES
----------------
CREATE TABLE IF NOT EXISTS FACTURAS(
  ID_FACTURA INT(11) NOT NULL AUTO_INCREMENT,
  RFC_EMISOR VARCHAR(15) NOT NULL,
  LINEA_EMISOR VARCHAR(10) NOT NULL,
  RAZON_SOCIAL_EMISOR VARCHAR(100),
  RFC_REMITENTE VARCHAR(15)NOT NULL,
  RAZON_SOCIAL_REMITENTE VARCHAR(100),
  LINEA_REMITENTE VARCHAR(10) NOT NULL,
  TIPO_DOCUMENTO VARCHAR(50) NOT NULL,
  SOLICITANTE  VARCHAR(400) NOT NULL,
  FOLIO VARCHAR(40) NOT NULL UNIQUE,
  FOLIO_PADRE VARCHAR(40),
  STATUS_FACTURA TINYINT UNSIGNED NOT NULL,
  STATUS_PAGO TINYINT UNSIGNED NOT NULL,
  STATUS_DEVOLUCION TINYINT UNSIGNED NOT NULL,
  STATUS_DETAIL VARCHAR(100),
  UUID VARCHAR(40),
  PACK_FACTURACION VARCHAR(15),
  NOTAS VARCHAR(400),
  FECHA_TIMBRADO  TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP,
  FECHA_CREACION TIMESTAMP,
  FECHA_CANCELADO TIMESTAMP,
  PRIMARY KEY (ID_FACTURA),
  UNIQUE (FOLIO)
);

CREATE TABLE IF NOT EXISTS CFDI(
  ID_CFDI INT(11) NOT NULL AUTO_INCREMENT,
  VERSION VARCHAR(10) NOT NULL,
  SERIE VARCHAR(40) NOT NULL,
  FOLIO VARCHAR(40) NOT NULL UNIQUE,
  SELLO VARCHAR(1000),
  NO_CERTIFICADO VARCHAR(30),
  CERTIFICADO VARCHAR(1000),
  MONEDA VARCHAR(10) NOT NULL,
  SUBTOTAL DECIMAL(15,2) UNSIGNED NOT NULL,
  DESCUENTO DECIMAL(15,2) UNSIGNED NOT NULL,
  TOTAL DECIMAL(15,2) UNSIGNED NOT NULL,
  TIPO_COMPROBANTE VARCHAR(50),
  METODO_PAGO VARCHAR(10) NOT NULL,
  FORMA_PAGO VARCHAR(10) NOT NULL,
  CONDICIONES_PAGO VARCHAR(50),
  LUGAR_EXPEDICION VARCHAR(10),
  USO_CFDI VARCHAR(5),
  REGIMEN_FISCAL VARCHAR(10),
  RFC_PROV_CERTIF VARCHAR(50),
  SELLO_CFD VARCHAR(1000),
  NO_CERTIFICADO_SAT VARCHAR(30),
  SELLO_SAT VARCHAR(1000),
  CADENA_ORIGINAL VARCHAR(1000),
  RFC_EMISOR VARCHAR(20) NOT NULL,
  RFC_RECEPTOR VARCHAR(20) NOT NULL,
  FECHA_TIMBRADO  TIMESTAMP,
  ID_FACTURA INTEGER(11) NOT NULL,
  PRIMARY KEY (ID_CFDI),
  UNIQUE(FOLIO),
  CONSTRAINT FK_CFDI_FACTURA
    FOREIGN KEY (ID_FACTURA)
    REFERENCES FACTURAS (ID_FACTURA)
);

CREATE TABLE IF NOT EXISTS CONCEPTOS(
  ID_CONCEPTO INT(11) NOT NULL AUTO_INCREMENT,
  CLAVE_PROD_SERV VARCHAR(10) NOT NULL,
  DESCRIPCION_CLAVE_UNIDAD VARCHAR(1000),
  NO_IDENTIFICACION VARCHAR(10),
  CANTIDAD DOUBLE(10,2),
  CLAVE_UNIDAD VARCHAR(5) NOT NULL,
  UNIDAD VARCHAR(100),
  DESCRIPCION VARCHAR(300),
  VALOR_UNITARIO DECIMAL(10,2) UNSIGNED NOT NULL,
  IMPORTE DECIMAL(15,2) UNSIGNED,
  DESCUENTO DECIMAL(10,2) UNSIGNED NOT NULL,
  ID_CFDI INT(11) NOT NULL,
  PRIMARY KEY(ID_CONCEPTO),
  CONSTRAINT FK_CONCEPTO_CFDI
    FOREIGN KEY (ID_CFDI)
    REFERENCES CFDI (ID_CFDI)
);

CREATE TABLE IF NOT EXISTS IMPUESTOS(
  ID_IMPUESTO INT(11) NOT NULL AUTO_INCREMENT,
  BASE DECIMAL(15,2) UNSIGNED NOT NULL,
  IMPUESTO VARCHAR(4),
  TIPO_FACTOR VARCHAR(10),
  TASA_CUOTA DECIMAL(2,2) UNSIGNED NOT NULL,
  IMPORTE DECIMAL(10,2) UNSIGNED NOT NULL,
  ID_CONCEPTO INT(11) NOT NULL,
  PRIMARY KEY (ID_IMPUESTO),
  CONSTRAINT FK_IMPUESTO_CONCEPTO
    FOREIGN KEY (ID_CONCEPTO)
    REFERENCES CONCEPTOS (ID_CONCEPTO)
);

CREATE TABLE IF NOT EXISTS RETENCIONES(
  ID_RETENCION INT(11) NOT NULL AUTO_INCREMENT,
  BASE DECIMAL(15,2) UNSIGNED NOT NULL,
  IMPUESTO VARCHAR(4),
  TIPO_FACTOR VARCHAR(10),
  TASA_CUOTA DECIMAL(2,2) UNSIGNED NOT NULL,
  IMPORTE DECIMAL(10,2) UNSIGNED NOT NULL,
  ID_CONCEPTO INT(11) NOT NULL,
  PRIMARY KEY (ID_RETENCION),
  CONSTRAINT FK_RETENCION_CONCEPTO
    FOREIGN KEY (ID_CONCEPTO)
    REFERENCES CONCEPTOS (ID_CONCEPTO)
);


CREATE TABLE IF NOT EXISTS FACTURA_FILES (
  FILE_ID int NOT NULL AUTO_INCREMENT,
  FOLIO varchar(40) NOT NULL,
  TIPO_ARCHIVO varchar(10) NOT NULL,
  DATA longblob,
  FECHA_CREACION timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`FILE_ID`),
  CONSTRAINT FK_FACTURA_FILE
    FOREIGN KEY (FOLIO)
    REFERENCES FACTURAS (FOLIO)
);



-------------------
---- TRANSFERENCIAS
--------------------
CREATE TABLE IF NOT EXISTS TRANSFERENCIAS(
	ID_TRANSFER INT(11) NOT NULL AUTO_INCREMENT,
	BANCO_RETIRO VARCHAR(30) NOT NULL,
	RFC_RETIRO VARCHAR(15) NOT NULL,
	CUENTA_RETIRO VARCHAR(50),
	LINEA_RETIRO VARCHAR(5) NOT NULL,
	BANCO_DEPOSITO VARCHAR(30) NOT NULL,
	RFC_DEPOSITO VARCHAR(15) NOT NULL,
	CUENTA_DEPOSITO VARCHAR(50),
	LINEA_DEPOSITO VARCHAR(5) NOT NULL,
	IMPORTE DOUBLE,
	FECHA_CREACION TIMESTAMP,
);

----------------
---CATALOGOS
----------------

CREATE TABLE IF NOT EXISTS CLAVE_UNIDAD(
	CLAVE VARCHAR(5) NOT NULL UNIQUE,
	TIPO VARCHAR(50) NOT NULL,
	DESCRIPCION VARCHAR(100),
	NOMBRE VARCHAR(50) NOT NULL,
  PRIMARY KEY (CLAVE) 
);

CREATE TABLE IF NOT EXISTS REGIMEN_FISCAL(
	CLAVE INT(10) NOT NULL UNIQUE,
	DESCRIPCION VARCHAR(100) NOT NULL,
	P_MORAL TINYINT(1) NOT NULL,
	P_FISICA TINYINT(1) NOT NULL,
	INICIO_VIGENCIA TIMESTAMP,
  PRIMARY KEY (CLAVE) 
);

CREATE TABLE IF NOT EXISTS USO_CFDI(
	CLAVE VARCHAR(10) NOT NULL UNIQUE,
	DESCRIPCION VARCHAR(100) NOT NULL,
	P_MORAL TINYINT(1) NOT NULL,
	P_FISICA TINYINT(1) NOT NULL,
	INICIO_VIGENCIA TIMESTAMP,
  PRIMARY KEY (CLAVE) 
);

CREATE TABLE IF NOT EXISTS CLAVE_PROD_SERV(
	CLAVE INT(10) NOT NULL UNIQUE,
	DESCRIPCION VARCHAR(500) NOT NULL,
	SIMILARES VARCHAR(500),
	INICIO_VIGENCIA TIMESTAMP,
  PRIMARY KEY (CLAVE) 
);

CREATE TABLE IF NOT EXISTS  FORMA_PAGO (
  CLAVE varchar(4) NOT NULL,
  DESCRIPCION varchar(100) NOT NULL,
  PRIMARY KEY (CLAVE)
) ;

CREATE TABLE IF NOT EXISTS STATUS_FACTURAS(
	ID_STATUS_FACTURA INT(10) NOT NULL UNIQUE,
	STATUS_VALIDACION VARCHAR(100) NOT NULL,
  STATUS_PAGO VARCHAR(100) NOT NULL,
  STATUS_DEVOLUCION VARCHAR(100) NOT NULL,
	FECHA_CREACION TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP,
  PRIMARY KEY (ID_STATUS_FACTURA) 
);

CREATE TABLE IF NOT EXISTS STATUS_PAGO(
	ID_STATUS_PAGO INT(10) NOT NULL UNIQUE,
	VALUE VARCHAR(50) NOT NULL,
  PRIMARY KEY (VALUE) 
);

CREATE TABLE IF NOT EXISTS STATUS_EVENTO(
	ID_STATUS_EVENTO INT(10) NOT NULL UNIQUE,
	VALUE VARCHAR(50) NOT NULL,
  PRIMARY KEY (VALUE) 
);
CREATE TABLE IF NOT EXISTS STATUS_DEVOLUCION(
	ID_STATUS_DEVOLUCION INT(10) NOT NULL UNIQUE,
	VALUE VARCHAR(50) NOT NULL,
  PRIMARY KEY (VALUE) 
);

CREATE TABLE IF NOT EXISTS GIROS(
	ID_GIRO INT(10) NOT NULL UNIQUE,
	NOMBRE VARCHAR(50) NOT NULL,
  FECHA_CREACION TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP
);

CREATE TABLE IF NOT EXISTS STATUS_REVISION(
	ID_STATUS_REVISION INT(10) NOT NULL UNIQUE,
	VALUE VARCHAR(50) NOT NULL,
  PRIMARY KEY (VALUE) 
);

CREATE TABLE IF NOT EXISTS RESOURCE_FILES(
	FILE_ID  INT(11) NOT NULL AUTO_INCREMENT,
	REFERENCIA VARCHAR(40) NOT NULL,
	TIPO_ARCHIVO VARCHAR(10) NOT NULL,
	TIPO_RECURSO VARCHAR(10) NOT NULL,
	DATA LONGBLOB NULL,
	FECHA_CREACION TIMESTAMP,
	PRIMARY KEY (FILE_ID)
);

